const CAMPSITES_RAW = [
  {
    id: 1,
    name: "Pineridge Summit Camp",
    location: "Rocky Mountain NP, Colorado",
    state: "Colorado",
    rating: 4.8,
    reviews: 142,
    tags: ["Tent", "Pet-Friendly", "Hiking"],
    amenities: ["Fire Pits", "Flush Toilets", "Potable Water", "Picnic Tables"],
    price: "$28/night",
    sites: 34,
    elevation: "9,200 ft",
    icon: "🏔️",
    gradient: "linear-gradient(135deg, #3d5a3e 0%, #2d4a2d 100%)",
    description:
      "Perched above the treeline with panoramic views of the Continental Divide, Pineridge Summit offers an unforgettable high-altitude camping experience. Wake up to marmots and elk grazing just beyond your tent. Stellar dark skies make this a favorite for stargazers.",
    reviews_list: [
      { author: "MargaretH", stars: 5, text: "Absolutely breathtaking views. The sunrise over the peaks was worth every bit of the drive up." },
      { author: "TrailDog92", stars: 5, text: "We've been coming here for 4 years. The fire pits are well-maintained and the rangers are super helpful." },
      { author: "NightSkyNate", stars: 4, text: "Dark skies are incredible. Bring layers — temps drop fast after sunset even in July." },
    ],
  },
  {
    id: 2,
    name: "Whispering Pines Hollow",
    location: "Ozark NF, Arkansas",
    state: "Arkansas",
    rating: 4.5,
    reviews: 89,
    tags: ["RV", "Family", "Fishing"],
    amenities: ["Electric Hookups", "Dump Station", "Showers", "Fish Cleaning Station"],
    price: "$35/night",
    sites: 52,
    elevation: "1,400 ft",
    icon: "🌲",
    gradient: "linear-gradient(135deg, #4a6741 0%, #2e4a2e 100%)",
    description:
      "Tucked along a cold-water creek shaded by ancient shortleaf pines, Whispering Pines is a sanctuary for families and anglers alike. The creek runs clear year-round, filled with trout. Kids can spend entire afternoons catching crawdads while adults relax in hammocks.",
    reviews_list: [
      { author: "FishingFred", stars: 5, text: "Caught my limit every single morning. The creek is crystal clear and the campsite is gorgeous." },
      { author: "MomOf3Campers", stars: 4, text: "Perfect for families. Kids loved the creek and the staff was incredibly welcoming." },
      { author: "OzarkWanderer", stars: 5, text: "The pine smell in the morning is unlike anything else. Will be back every fall." },
    ],
  },
  {
    id: 3,
    name: "Redrock Canyon Basecamp",
    location: "Escalante, Utah",
    state: "Utah",
    rating: 4.9,
    reviews: 214,
    tags: ["Dispersed", "Hiking", "Photography"],
    amenities: ["Vault Toilets", "Bear Boxes", "Trailhead Access"],
    price: "$18/night",
    sites: 16,
    elevation: "5,800 ft",
    icon: "🏜️",
    gradient: "linear-gradient(135deg, #8b4513 0%, #5c3317 100%)",
    description:
      "Step into a Mars-like landscape of towering sandstone fins and slot canyons painted in every shade of red and orange. This primitive camp sits at the trailhead of four world-class canyon hikes. No crowds, no noise — just rock, sky, and stars.",
    reviews_list: [
      { author: "CanyonCrawler", stars: 5, text: "The slot canyon at sunrise is a religious experience. Get up early — it's worth it." },
      { author: "DesertPhotog", stars: 5, text: "Every direction is a shot. I've never deleted so few photos from a single trip." },
      { author: "BackpackBeth", stars: 4, text: "Very primitive, bring all your water. But the solitude is absolutely worth it." },
    ],
  },
  {
    id: 4,
    name: "Lakeshore Meadows",
    location: "Boundary Waters, Minnesota",
    state: "Minnesota",
    rating: 4.6,
    reviews: 178,
    tags: ["Canoe", "Pet-Friendly", "Paddling"],
    amenities: ["Canoe Launch", "Picnic Tables", "Fire Rings", "Vault Toilets"],
    price: "$22/night",
    sites: 28,
    elevation: "1,356 ft",
    icon: "🛶",
    gradient: "linear-gradient(135deg, #2c5f6e 0%, #1a3d4a 100%)",
    description:
      "Loons calling at dusk, moose wading in the shallows at dawn — Lakeshore Meadows drops you right into the legendary BWCA experience. Flat sites sit just steps from the water, perfect for portage trips or lazy days paddling the shoreline.",
    reviews_list: [
      { author: "PaddlePete", stars: 5, text: "Heard loons every single night. The canoe launch is in great shape and the sites have great lake views." },
      { author: "MNWilderness", stars: 4, text: "Bring bug spray in June, but the fishing and paddling make it 100% worth it." },
      { author: "QuietLakeLou", stars: 5, text: "Most peaceful place I've ever camped. Woke up to a moose literally ten feet from my tent." },
    ],
  },
  {
    id: 5,
    name: "Coastal Bluff Retreat",
    location: "Point Reyes NS, California",
    state: "California",
    rating: 4.7,
    reviews: 301,
    tags: ["Hike-in", "Ocean Views", "Wildlife"],
    amenities: ["Composting Toilets", "Food Lockers", "Water Spigot"],
    price: "$30/night",
    sites: 20,
    elevation: "240 ft",
    icon: "🌊",
    gradient: "linear-gradient(135deg, #2a5c8a 0%, #1a3a5c 100%)",
    description:
      "A 2-mile hike rewards you with a cliffside camp perched above the Pacific. Elephant seals bark on the beaches below, gray whales breach offshore in winter, and wildflowers carpet the bluffs in spring. One of the most dramatic camp settings on the West Coast.",
    reviews_list: [
      { author: "WhaleDan", stars: 5, text: "Saw four gray whales from camp in February. The sunsets here are surreal." },
      { author: "PtReyesRegular", stars: 5, text: "I've been here every year for 6 years. It never gets old. Book way in advance." },
      { author: "BluffHiker", stars: 4, text: "The hike in is easy and totally worth it. Mornings are foggy and magical." },
    ],
  },
  {
    id: 6,
    name: "Glacier Creek Flats",
    location: "North Cascades NP, Washington",
    state: "Washington",
    rating: 4.8,
    reviews: 95,
    tags: ["Backcountry", "Climbing", "Wildflowers"],
    amenities: ["Bear Canisters Required", "Vault Toilets", "Ranger Station Nearby"],
    price: "$20/night",
    sites: 12,
    elevation: "4,100 ft",
    icon: "❄️",
    gradient: "linear-gradient(135deg, #3a6b8a 0%, #1e3f5a 100%)",
    description:
      "Surrounded by jagged peaks and fed by milky glacial meltwater, this remote camp is a paradise for alpinists and wildflower enthusiasts. The meadows burst into color July–August, and the creek crossing into camp makes for an adventurous entrance.",
    reviews_list: [
      { author: "AlpineAli", stars: 5, text: "The wildflowers in late July are absolutely insane. Like walking through a painting." },
      { author: "CascadesClimber", stars: 5, text: "Used as a base for a 3-day ridge traverse. Perfect location, clean water nearby." },
      { author: "GlacierGazer", stars: 4, text: "Get permits early — this fills up fast. Worth every bit of the effort." },
    ],
  },
  {
    id: 7,
    name: "Longleaf Pine Bottoms",
    location: "Kisatchie NF, Louisiana",
    state: "Louisiana",
    rating: 4.3,
    reviews: 61,
    tags: ["Family", "Birding", "Quiet"],
    amenities: ["Flush Toilets", "Hot Showers", "Playgrounds", "Picnic Shelters"],
    price: "$24/night",
    sites: 44,
    elevation: "240 ft",
    icon: "🌿",
    gradient: "linear-gradient(135deg, #4a6a3a 0%, #2d4a20 100%)",
    description:
      "A hidden gem in the Deep South, this longleaf pine forest is one of the rarest ecosystems in North America. Birdwatchers flock here for red-cockaded woodpeckers and painted buntings. Warm nights, fireflies, and the smell of pine resin define the experience.",
    reviews_list: [
      { author: "BirdLadySue", stars: 5, text: "Spotted 34 species in one morning walk. The longleaf ecosystem is incredibly special." },
      { author: "SouthernCamper", stars: 4, text: "Very well-maintained campground. The facilities are clean and the staff is friendly." },
      { author: "FireflyFan", stars: 4, text: "Come in June for the fireflies. It looks like the whole forest is twinkling." },
    ],
  },
  {
    id: 8,
    name: "Thunder Basin Prairie Camp",
    location: "Thunder Basin NG, Wyoming",
    state: "Wyoming",
    rating: 4.4,
    reviews: 47,
    tags: ["Dispersed", "Wildlife", "Stargazing"],
    amenities: ["Vault Toilets", "Fire Rings"],
    price: "$10/night",
    sites: 8,
    elevation: "4,900 ft",
    icon: "⭐",
    gradient: "linear-gradient(135deg, #6b5a2a 0%, #3d3215 100%)",
    description:
      "Endless rolling prairie under a sky that seems twice as big as anywhere else. Pronghorn antelope graze at the edge of camp, and the Milky Way stretches from horizon to horizon on clear nights. True wide-open-spaces camping at its most honest.",
    reviews_list: [
      { author: "PronghorPaul", stars: 5, text: "Woke up surrounded by 40 pronghorn antelope. Absolute bucket-list morning." },
      { author: "DarkSkyStan", stars: 5, text: "Zero light pollution. Genuinely the best stars I've ever seen in the lower 48." },
      { author: "PrairieWalker", stars: 4, text: "Very basic facilities, but that's the point. Bring everything you need." },
    ],
  },
  {
    id: 9,
    name: "Hemlock Hollow Retreat",
    location: "Monongahela NF, West Virginia",
    state: "West Virginia",
    rating: 4.6,
    reviews: 112,
    tags: ["Family", "Fly Fishing", "Waterfalls"],
    amenities: ["Flush Toilets", "Hot Showers", "Potable Water", "Picnic Tables"],
    price: "$26/night",
    sites: 38,
    elevation: "2,800 ft",
    icon: "🌊",
    gradient: "linear-gradient(135deg, #2d5a3d 0%, #1a3d28 100%)",
    description:
      "Nestled in a cool hemlock-shaded gorge where two cold-water trout streams meet, this camp has everything: great fishing, easy waterfall hikes, and a family-friendly atmosphere. The hemlock canopy keeps things 10° cooler than the valley floor all summer.",
    reviews_list: [
      { author: "TroutWhisperer", stars: 5, text: "The Elk River section here is world-class for wild trout. Incredible experience." },
      { author: "WVNatureFan", stars: 4, text: "Visited in October for fall colors and it blew me away. Very underrated." },
      { author: "CoolCampCarl", stars: 5, text: "Escaped 95-degree heat in the valley and camped in 72-degree bliss. Worth the drive." },
    ],
  },
  {
    id: 10,
    name: "Saguaro Dusk Camp",
    location: "Sonoran Desert, Arizona",
    state: "Arizona",
    rating: 4.5,
    reviews: 88,
    tags: ["Desert", "Stargazing", "Photography"],
    amenities: ["Vault Toilets", "Water Station", "Ramadas"],
    price: "$20/night",
    sites: 22,
    elevation: "2,600 ft",
    icon: "🌵",
    gradient: "linear-gradient(135deg, #7a4e2d 0%, #4a2d15 100%)",
    description:
      "Camp among 150-year-old saguaro cacti as the sun sets the sky ablaze with orange and violet. Elf owls nest in the cacti overhead, Gila woodpeckers hammer at dawn, and coyotes serenade the moon. Winter camping here is mild and magical.",
    reviews_list: [
      { author: "DesertDawnDave", stars: 5, text: "The sunset colors reflecting off the saguaros are beyond words. Pure magic." },
      { author: "SonoranSally", stars: 5, text: "Owls hooting all night, roadrunner at breakfast. Desert birding paradise." },
      { author: "WinterCamper", stars: 4, text: "December here is perfect — cool days, cold nights, zero bugs. Ideal." },
    ],
  },
  {
    id: 11,
    name: "Foggy Hollow Cove",
    location: "Acadia NP, Maine",
    state: "Maine",
    rating: 4.7,
    reviews: 189,
    tags: ["Ocean Views", "Hiking", "Kayaking"],
    amenities: ["Flush Toilets", "Hot Showers", "Kayak Storage", "Ranger Programs"],
    price: "$32/night",
    sites: 30,
    elevation: "140 ft",
    icon: "🦞",
    gradient: "linear-gradient(135deg, #2a4a6a 0%, #152a3d 100%)",
    description:
      "Rocky Maine coastline, lobster boats in the fog, and the cry of seagulls over spruce forest — Foggy Hollow Cove is New England camping at its most atmospheric. Just outside Acadia's network of carriage roads, it's a perfect base for cyclists and hikers.",
    reviews_list: [
      { author: "MaineShoreMarcy", stars: 5, text: "Went for the lobster rolls, stayed for the incredible fog and coastline." },
      { author: "AcadiaCyclist", stars: 5, text: "Biked every carriage road in the park from this camp. Couldn't be better located." },
      { author: "FogLover", stars: 4, text: "The morning fog rolling in off the ocean is hauntingly beautiful. Very peaceful." },
    ],
  },
  {
    id: 12,
    name: "Aspen Grove High Camp",
    location: "White River NF, Colorado",
    state: "Colorado",
    rating: 4.9,
    reviews: 203,
    tags: ["Tent", "Fall Foliage", "Hiking"],
    amenities: ["Vault Toilets", "Water", "Fire Rings", "Trailhead Parking"],
    price: "$22/night",
    sites: 18,
    elevation: "10,400 ft",
    icon: "🍂",
    gradient: "linear-gradient(135deg, #7a6a2a 0%, #4a3e15 100%)",
    description:
      "In late September, this high-elevation camp transforms into a cathedral of gold as thousands of aspen trees turn simultaneously. The shimmering of leaves in the mountain breeze is a phenomenon you'll hear before you see. Book months ahead for peak fall.",
    reviews_list: [
      { author: "AspenAdmirer", stars: 5, text: "Peak fall weekend was absolutely transcendent. The sound of aspen leaves is otherworldly." },
      { author: "ColoradoCarrie", stars: 5, text: "Hiked to a 13er from camp. Views were incredible. Aspen groves turned perfectly." },
      { author: "FallFoliageFan", stars: 5, text: "Drove 6 hours for this. Zero regrets. Will be back every single October." },
    ],
  },
  {
    id: 13,
    name: "Bayou Cypress Camp",
    location: "Atchafalaya Basin, Louisiana",
    state: "Louisiana",
    rating: 4.2,
    reviews: 53,
    tags: ["Paddling", "Wildlife", "Unique"],
    amenities: ["Canoe Launch", "Pit Toilets", "Covered Pavilion"],
    price: "$15/night",
    sites: 10,
    elevation: "12 ft",
    icon: "🐊",
    gradient: "linear-gradient(135deg, #2a4a2a 0%, #152a15 100%)",
    description:
      "The largest river swamp in North America, the Atchafalaya offers a camping experience unlike anywhere else in the US. Ancient bald cypress draped in Spanish moss rise from the dark water. Alligators, herons, and roseate spoonbills are your neighbors.",
    reviews_list: [
      { author: "SwampSteve", stars: 5, text: "Paddled for 3 days through cypress groves. Felt like a different world entirely." },
      { author: "WildlifeWatcher", stars: 4, text: "Saw 3 alligators, 12 species of birds, and a nutria on day one. Unbelievable." },
      { author: "LouisianaLocal", stars: 4, text: "Basic facilities but the natural beauty is off the charts. Come at sunrise." },
    ],
  },
  {
    id: 14,
    name: "Tundra Rim Outpost",
    location: "Denali NP, Alaska",
    state: "Alaska",
    rating: 4.8,
    reviews: 74,
    tags: ["Backcountry", "Wildlife", "Midnight Sun"],
    amenities: ["Bear-Resistant Containers Required", "Bus Access Only", "Ranger Patrol"],
    price: "$16/night",
    sites: 6,
    elevation: "3,900 ft",
    icon: "🐻",
    gradient: "linear-gradient(135deg, #2d4a5c 0%, #152530 100%)",
    description:
      "One of the most remote and raw camping experiences in the national park system. Accessible only by park bus, the tundra here offers grizzly bear sightings, caribou migrations, and in summer, 20+ hours of daylight. Denali herself dominates the western horizon.",
    reviews_list: [
      { author: "AlaskaAlex", stars: 5, text: "Grizzly with two cubs walked through camp at 2am. Still light outside. Alaska is unreal." },
      { author: "MidnightSunMeg", stars: 5, text: "Sat outside reading at midnight in full daylight. Surreal and unforgettable." },
      { author: "DenaliDreamer", stars: 5, text: "Hardest permit to get in Alaska. Worth every year I waited on the waitlist." },
    ],
  },
  {
    id: 15,
    name: "Blue Ridge Ridgeline",
    location: "Shenandoah NP, Virginia",
    state: "Virginia",
    rating: 4.5,
    reviews: 267,
    tags: ["Family", "Skyline Drive", "Fall Foliage"],
    amenities: ["Flush Toilets", "Showers", "Camp Store", "Amphitheater"],
    price: "$30/night",
    sites: 65,
    elevation: "3,600 ft",
    icon: "🌄",
    gradient: "linear-gradient(135deg, #3d5a3e 0%, #253525 100%)",
    description:
      "Sitting astride the crest of the Blue Ridge with sweeping valley views east and west, this is Shenandoah's most beloved frontcountry camp. Deer wander through sites at dusk, and the Appalachian Trail passes directly through the campground.",
    reviews_list: [
      { author: "ShenandoahSam", stars: 5, text: "AT through-hikers camping next to us shared wild stories. Magical community vibe." },
      { author: "DrivingTheDrive", stars: 4, text: "Perfect base for Skyline Drive. Very well-run, great amenities for families." },
      { author: "ValleyViewer", stars: 5, text: "Watched the fog fill the valley below at sunrise from my camp chair. Spectacular." },
    ],
  },
  {
    id: 16,
    name: "Lava Tube Basecamp",
    location: "Craters of the Moon NM, Idaho",
    state: "Idaho",
    rating: 4.4,
    reviews: 82,
    tags: ["Unique", "Geology", "Dark Sky"],
    amenities: ["Flush Toilets", "Potable Water", "Visitor Center Access"],
    price: "$20/night",
    sites: 42,
    elevation: "5,900 ft",
    icon: "🌋",
    gradient: "linear-gradient(135deg, #3a3a3a 0%, #1a1a1a 100%)",
    description:
      "Camp on a literal lava flow at one of America's most otherworldly landscapes. During the day, explore lava tubes, spatter cones, and obsidian flows. At night, a certified International Dark Sky Park delivers some of the most spectacular stargazing in the West.",
    reviews_list: [
      { author: "GeoGeek", stars: 5, text: "Crawled through a 1,000-foot lava tube. Absolutely prehistoric and incredible." },
      { author: "StargazerStan", stars: 5, text: "No moon, no light pollution, billions of stars. The Milky Way above black lava. Wow." },
      { author: "MoonScapeMaria", stars: 4, text: "Feels like another planet. Hot during the day but stunning in every direction." },
    ],
  },
  {
    id: 17,
    name: "Smoky Holler Hollow",
    location: "Great Smoky Mountains NP, Tennessee",
    state: "Tennessee",
    rating: 4.6,
    reviews: 345,
    tags: ["Family", "Waterfall", "Fall Foliage"],
    amenities: ["Flush Toilets", "Hot Showers", "Accessible Sites", "Amphitheater"],
    price: "$29/night",
    sites: 80,
    elevation: "1,800 ft",
    icon: "🌫️",
    gradient: "linear-gradient(135deg, #3d5c3d 0%, #1e2e1e 100%)",
    description:
      "Wrapped in the perpetual blue haze that gives these mountains their name, this beloved camp sits next to a rushing mountain stream. Synchronous fireflies in June draw visitors from around the world, and the fall colors rival anywhere in America.",
    reviews_list: [
      { author: "FireflyChaser", stars: 5, text: "Synchronous fireflies are a genuine natural wonder. Everyone should see this once." },
      { author: "SmokyMountainMom", stars: 5, text: "Brought 3 kids and they all said it was their favorite camping trip ever." },
      { author: "HazeHiker", stars: 4, text: "Crowded in peak season but the surrounding wilderness makes it worth it." },
    ],
  },
  {
    id: 18,
    name: "Mesa Verde Starcamp",
    location: "Mesa Verde NP, Colorado",
    state: "Colorado",
    rating: 4.7,
    reviews: 156,
    tags: ["Cultural", "Stargazing", "History"],
    amenities: ["Flush Toilets", "Showers", "Gift Shop", "Evening Programs"],
    price: "$34/night",
    sites: 45,
    elevation: "7,000 ft",
    icon: "🏺",
    gradient: "linear-gradient(135deg, #6b4a2a 0%, #3d2510 100%)",
    description:
      "Camp on the same mesa where Ancestral Puebloans built their remarkable cliff dwellings over 700 years ago. Ranger-led evening programs bring history to life, and the high desert elevation means cool nights and jaw-dropping star density overhead.",
    reviews_list: [
      { author: "HistoryHiker", stars: 5, text: "The evening cliff dwelling tour by torchlight was one of the best experiences of my life." },
      { author: "DesertDreamer", stars: 4, text: "Woke up to a brilliant sunrise over the canyon. Made breakfast feeling like an ancient farmer." },
      { author: "MesaMarco", stars: 5, text: "Perfect mix of culture, nature, and stars. Bring a good sleeping bag for cold nights." },
    ],
  },
  {
    id: 19,
    name: "Tallgrass Prairie Vista",
    location: "Flint Hills, Kansas",
    state: "Kansas",
    rating: 4.3,
    reviews: 39,
    tags: ["Prairie", "Birding", "Solitude"],
    amenities: ["Pit Toilets", "Water Pump", "Fire Rings"],
    price: "$12/night",
    sites: 14,
    elevation: "1,440 ft",
    icon: "🌾",
    gradient: "linear-gradient(135deg, #7a6a3a 0%, #4a3e1e 100%)",
    description:
      "One of the last remaining tallgrass prairie ecosystems in North America. Wind waves through 8-foot bluestem grass around your tent, greater prairie chickens boom at dawn, and the treeless horizon stretches forever in every direction. Rare, beautiful solitude.",
    reviews_list: [
      { author: "PrairiePhil", stars: 5, text: "The wind in the tallgrass sounds like the ocean. Completely meditative experience." },
      { author: "GrasslandBirder", stars: 4, text: "Dickcissels, bobolinks, prairie chickens — incredible grassland birding." },
      { author: "SolitudeSeeker", stars: 5, text: "Camped here alone for 3 nights. Perfect peace. Most people don't even know this exists." },
    ],
  },
  {
    id: 20,
    name: "Olympic Rainforest Camp",
    location: "Hoh Rainforest, Washington",
    state: "Washington",
    rating: 4.8,
    reviews: 221,
    tags: ["Rainforest", "Wildlife", "Photography"],
    amenities: ["Flush Toilets", "Potable Water", "Amphitheater", "Accessible Trails"],
    price: "$24/night",
    sites: 36,
    elevation: "578 ft",
    icon: "🌿",
    gradient: "linear-gradient(135deg, #2a5a3a 0%, #152a1e 100%)",
    description:
      "The Hoh is one of only four temperate rainforests in the world, and camping here feels like stepping into a Tolkien novel. Massive old-growth Sitka spruce draped in club moss, Roosevelt elk grazing in clearings, and the absolute silence of 140 inches of annual rainfall absorbed by millennia of moss.",
    reviews_list: [
      { author: "MossAndMist", stars: 5, text: "The Hall of Mosses at dusk felt ancient and sacred. Truly one of earth's special places." },
      { author: "RooseveltRandy", stars: 5, text: "Huge elk herd walked through camp at sunrise. Incredible, quiet, humbling." },
      { author: "RainLover", stars: 4, text: "It rained the whole time and I didn't care at all. The forest just comes alive in rain." },
    ],
  },
  {
    id: 21,
    name: "Pecos Ridge Camp",
    location: "Santa Fe NF, New Mexico",
    state: "New Mexico",
    rating: 4.6,
    reviews: 118,
    tags: ["Backcountry", "Hiking", "Fishing"],
    amenities: ["Vault Toilets", "River Access", "Bear Boxes"],
    price: "$21/night",
    sites: 24,
    elevation: "8,700 ft",
    icon: "🏕️",
    gradient: "linear-gradient(135deg, #6a4b2a 0%, #3b2a16 100%)",
    description:
      "Set along a cold mountain river beneath ponderosa pines, Pecos Ridge is a classic basecamp for alpine day hikes and fly-fishing. Afternoon storms cool things quickly, and evenings usually end with clear, star-heavy skies.",
    reviews_list: [
      { author: "HighCountryHal", stars: 5, text: "Great trail access and quiet campsites. Perfect place to acclimate before higher peaks." },
      { author: "NMFisher", stars: 4, text: "River fishing was solid and the campground was clean. Bring layers for chilly nights." },
      { author: "MesaMia", stars: 5, text: "Sunsets through the pines were unreal. One of my favorite New Mexico camps." },
    ],
  },
  {
    id: 22,
    name: "Lost Coast Bluff Camp",
    location: "King Range NCA, California",
    state: "California",
    rating: 4.7,
    reviews: 96,
    tags: ["Hike-in", "Ocean Views", "Wildlife"],
    amenities: ["Composting Toilets", "Food Storage Lockers", "Water Spigot"],
    price: "$33/night",
    sites: 14,
    elevation: "180 ft",
    icon: "🌊",
    gradient: "linear-gradient(135deg, #2f5d7a 0%, #173245 100%)",
    description:
      "A narrow strip of camp above a dramatic wave-battered shoreline, this spot delivers sea stacks, tide pools, and constant ocean wind. It's a favorite stop for Lost Coast Trail hikers who want one more night by the Pacific.",
    reviews_list: [
      { author: "CoastWalker", stars: 5, text: "Woke up to sea lions and fog rolling across the bluffs. Incredible place." },
      { author: "TideTableTom", stars: 4, text: "Amazing views, but plan around tides if you are hiking in and out." },
      { author: "SaltAirSam", stars: 5, text: "Perfect overnight stop on the trail. Sunset colors over the water were wild." },
    ],
  },
  {
    id: 23,
    name: "Juniper Basin Camp",
    location: "Coconino NF, Arizona",
    state: "Arizona",
    rating: 4.4,
    reviews: 72,
    tags: ["Tent", "Family", "Stargazing"],
    amenities: ["Flush Toilets", "Potable Water", "Picnic Tables", "Fire Rings"],
    price: "$19/night",
    sites: 31,
    elevation: "6,500 ft",
    icon: "🌌",
    gradient: "linear-gradient(135deg, #4b3b66 0%, #241b34 100%)",
    description:
      "Between red-rock country and high desert forest, Juniper Basin is known for cool nights and crisp dark skies. Short interpretive loops near camp make it a good fit for families and new campers.",
    reviews_list: [
      { author: "NightLensNick", stars: 5, text: "Excellent dark skies for Milky Way shots and super easy setup sites." },
      { author: "DesertDad", stars: 4, text: "Great family campground with simple trail options nearby." },
      { author: "StargazeSue", stars: 4, text: "Quiet at night and easy access from town. Good value." },
    ],
  },
  {
    id: 24,
    name: "Granite Pass Meadow",
    location: "Sierra NF, California",
    state: "California",
    rating: 4.8,
    reviews: 134,
    tags: ["Backcountry", "Wildflowers", "Hiking"],
    amenities: ["Bear Boxes", "Trailhead Access", "Creek Water Nearby"],
    price: "$25/night",
    sites: 19,
    elevation: "7,900 ft",
    icon: "⛰️",
    gradient: "linear-gradient(135deg, #4f6a78 0%, #283743 100%)",
    description:
      "Granite slabs, wide meadows, and easy access to high country passes make this a go-to Sierra basecamp. Summer wildflowers attract photographers, while shoulder season brings fewer crowds and crisp air.",
    reviews_list: [
      { author: "PeakBaggerPaige", stars: 5, text: "Excellent jumping-off point for long ridge hikes. Camp was quiet and clean." },
      { author: "SierraScout", stars: 5, text: "Meadow blooms in July were incredible. Lots of day-hike options from camp." },
      { author: "TrailMiles", stars: 4, text: "Popular on weekends but still worth it for the views alone." },
    ],
  },
  {
    id: 25,
    name: "Cedar Run Hollow",
    location: "Allegheny NF, Pennsylvania",
    state: "Pennsylvania",
    rating: 4.5,
    reviews: 87,
    tags: ["Family", "Pet-Friendly", "Hiking"],
    amenities: ["Flush Toilets", "Showers", "Potable Water", "Camp Store"],
    price: "$23/night",
    sites: 48,
    elevation: "1,920 ft",
    icon: "🌲",
    gradient: "linear-gradient(135deg, #3b5b3d 0%, #1f3322 100%)",
    description:
      "Tucked among hemlock and cedar with a stream running through the valley floor, Cedar Run Hollow offers easy terrain and calm evenings. Several moderate waterfall trails begin within a short drive of camp.",
    reviews_list: [
      { author: "EastCoastErin", stars: 5, text: "Really nice facilities and great access to nearby waterfall hikes." },
      { author: "CreeksideCamper", stars: 4, text: "Loved hearing the stream at night. Solid family campground." },
      { author: "PinePathPat", stars: 4, text: "Not too crowded midweek and staff was very friendly." },
    ],
  },
  {
    id: 26,
    name: "Blackwater Ridge Camp",
    location: "Dolly Sods, West Virginia",
    state: "West Virginia",
    rating: 4.7,
    reviews: 103,
    tags: ["Backcountry", "Wildlife", "Hiking"],
    amenities: ["Bear Boxes", "Stream Access", "Trailhead Parking"],
    price: "$19/night",
    sites: 22,
    elevation: "4,200 ft",
    icon: "🦌",
    gradient: "linear-gradient(135deg, #415a42 0%, #1f2e20 100%)",
    description: "A high plateau camp with open heath barrens, red spruce pockets, and broad sunrise views. Popular with backpackers using it as a launch point for loops through Dolly Sods wilderness.",
    reviews_list: [
      { author: "RidgeRunner", stars: 5, text: "Incredible sunrise and lots of wildlife activity at dusk." },
      { author: "SodsScout", stars: 4, text: "Great trails, muddy in places, still absolutely worth it." },
      { author: "PineWind", stars: 5, text: "One of the most unique landscapes in the Mid-Atlantic." },
    ],
  },
  {
    id: 27,
    name: "Cascade Fork Camp",
    location: "Uinta-Wasatch NF, Utah",
    state: "Utah",
    rating: 4.5,
    reviews: 77,
    tags: ["Family", "Hiking", "Fishing"],
    amenities: ["Flush Toilets", "Picnic Tables", "Fire Rings", "Water Spigot"],
    price: "$24/night",
    sites: 35,
    elevation: "7,100 ft",
    icon: "🏞️",
    gradient: "linear-gradient(135deg, #3a6670 0%, #203841 100%)",
    description: "Set where two creeks meet beneath aspen groves, Cascade Fork is an easy-access mountain camp with cool summer nights and short waterfall hikes nearby.",
    reviews_list: [
      { author: "FlyLineFred", stars: 5, text: "Nice stream access and super clean campground." },
      { author: "AspenAmy", stars: 4, text: "Great family trip, easy trails for kids." },
      { author: "TrailToast", stars: 4, text: "Good shade and pleasant temps even in July." },
    ],
  },
  {
    id: 28,
    name: "Palisade Lake Camp",
    location: "Sawbuck Range, Nevada",
    state: "Nevada",
    rating: 4.4,
    reviews: 64,
    tags: ["Tent", "Stargazing", "Wildlife"],
    amenities: ["Vault Toilets", "Boat Launch", "Fire Rings"],
    price: "$17/night",
    sites: 18,
    elevation: "6,200 ft",
    icon: "🌠",
    gradient: "linear-gradient(135deg, #49556f 0%, #262d3b 100%)",
    description: "A remote high-desert lake campground known for still water mornings and dark, clear skies. Bring layers: days are warm but nights cool quickly.",
    reviews_list: [
      { author: "Skywatcher", stars: 5, text: "Some of the best stargazing I've had all year." },
      { author: "DesertLine", stars: 4, text: "Quiet and uncrowded with beautiful lake reflections." },
      { author: "NVNomad", stars: 4, text: "Basic amenities but a peaceful place to reset." },
    ],
  },
  {
    id: 29,
    name: "Willow Bend Camp",
    location: "Mark Twain NF, Missouri",
    state: "Missouri",
    rating: 4.3,
    reviews: 58,
    tags: ["Family", "Pet-Friendly", "Fishing"],
    amenities: ["Showers", "Electric Hookups", "Dump Station", "Camp Store"],
    price: "$27/night",
    sites: 54,
    elevation: "960 ft",
    icon: "🎣",
    gradient: "linear-gradient(135deg, #4a7048 0%, #294129 100%)",
    description: "A riverbend campground with broad gravel bars, easy float access, and shaded loops for RV and tent camping. Popular for weekend trips and summer fishing.",
    reviews_list: [
      { author: "OzarkFloat", stars: 4, text: "Great river access and friendly camp hosts." },
      { author: "MissouriMoon", stars: 4, text: "Family-friendly and easy to navigate." },
      { author: "CreekCam", stars: 5, text: "Perfect long weekend spot with solid facilities." },
    ],
  },
  {
    id: 30,
    name: "Timberline Shelf Camp",
    location: "San Juan NF, Colorado",
    state: "Colorado",
    rating: 4.8,
    reviews: 144,
    tags: ["Backcountry", "Hiking", "Photography"],
    amenities: ["Bear Boxes", "Vault Toilets", "Trailhead Access"],
    price: "$26/night",
    sites: 15,
    elevation: "10,100 ft",
    icon: "📷",
    gradient: "linear-gradient(135deg, #58707d 0%, #2f3d45 100%)",
    description: "High above the valley floor, Timberline Shelf delivers alpine views, quick access to ridgelines, and brilliant morning light for photographers.",
    reviews_list: [
      { author: "AlpineFrame", stars: 5, text: "Stunning views right from camp and excellent trail links." },
      { author: "SwitchbackSue", stars: 5, text: "Cool nights, clean sites, and a great base for 14er training." },
      { author: "PeakPixel", stars: 4, text: "A little exposed to wind, but incredible scenery." },
    ],
  },
  {
    id: 31,
    name: "Pine Cone Flats",
    location: "Adirondack Park, New York",
    state: "New York",
    rating: 4.6,
    reviews: 98,
    tags: ["Canoe", "Family", "Hiking"],
    amenities: ["Canoe Launch", "Flush Toilets", "Potable Water", "Picnic Tables"],
    price: "$25/night",
    sites: 33,
    elevation: "1,540 ft",
    icon: "🛶",
    gradient: "linear-gradient(135deg, #3f5f73 0%, #203241 100%)",
    description: "A mixed forest campground with small ponds, gentle paddling routes, and easy mountain trails nearby. Excellent shoulder-season color in September and October.",
    reviews_list: [
      { author: "NorthwoodsNina", stars: 5, text: "Great base for paddling and short summit hikes." },
      { author: "MapleMist", stars: 4, text: "Beautiful fall colors and well-maintained facilities." },
      { author: "LakeLoop", stars: 5, text: "Very relaxing campground with lots to do nearby." },
    ],
  },
  {
    id: 32,
    name: "Coyote Draw Camp",
    location: "Capitol Reef, Utah",
    state: "Utah",
    rating: 4.7,
    reviews: 86,
    tags: ["Dispersed", "Photography", "Stargazing"],
    amenities: ["Vault Toilets", "Water Station", "Trail Access"],
    price: "$16/night",
    sites: 12,
    elevation: "5,300 ft",
    icon: "🌌",
    gradient: "linear-gradient(135deg, #7a5332 0%, #402b1a 100%)",
    description: "Set among domes and cliffs of sandstone, Coyote Draw offers quiet nights and dramatic skies. A favorite for astrophotography and sunrise canyon walks.",
    reviews_list: [
      { author: "RedRockRay", stars: 5, text: "Dark skies and huge views, exactly what we wanted." },
      { author: "DustTrail", stars: 4, text: "Simple amenities but amazing location." },
      { author: "ShutterJune", stars: 5, text: "Excellent light at dawn and dusk." },
    ],
  },
  {
    id: 33,
    name: "Bear Creek Terrace",
    location: "Pisgah NF, North Carolina",
    state: "North Carolina",
    rating: 4.5,
    reviews: 112,
    tags: ["Family", "Waterfall", "Hiking"],
    amenities: ["Flush Toilets", "Showers", "Water", "Picnic Tables"],
    price: "$28/night",
    sites: 40,
    elevation: "3,100 ft",
    icon: "💧",
    gradient: "linear-gradient(135deg, #3d6752 0%, #20372a 100%)",
    description: "Nestled in rhododendron thickets beside a cascading creek, this camp is close to several classic Blue Ridge waterfall trails and scenic drives.",
    reviews_list: [
      { author: "BlueRidgeBen", stars: 5, text: "Easy access to waterfalls and lovely creek sounds at night." },
      { author: "TrailCarla", stars: 4, text: "Solid facilities and beautiful forest." },
      { author: "FogFern", stars: 4, text: "Great basecamp for a week of day hikes." },
    ],
  },
  {
    id: 34,
    name: "Sand Dune Basin Camp",
    location: "Great Sand Dunes NP, Colorado",
    state: "Colorado",
    rating: 4.6,
    reviews: 125,
    tags: ["Desert", "Family", "Stargazing"],
    amenities: ["Flush Toilets", "Water Spigot", "Fire Rings", "Ranger Programs"],
    price: "$23/night",
    sites: 32,
    elevation: "8,120 ft",
    icon: "🏜️",
    gradient: "linear-gradient(135deg, #8a6a3a 0%, #4a371d 100%)",
    description: "A high-elevation desert campground at the base of North America's tallest dunes. Days are warm, nights are cold, and skies are exceptionally clear.",
    reviews_list: [
      { author: "DuneDash", stars: 5, text: "Sunset on the dunes and stars at night were amazing." },
      { author: "ColdNight", stars: 4, text: "Bring warm gear even in summer." },
      { author: "SandStep", stars: 5, text: "Great mix of scenery and family-friendly access." },
    ],
  },
  {
    id: 35,
    name: "Big Spruce Landing",
    location: "Baxter SP, Maine",
    state: "Maine",
    rating: 4.8,
    reviews: 91,
    tags: ["Backcountry", "Hiking", "Wildlife"],
    amenities: ["Lean-to Sites", "Water Pump", "Bear Storage"],
    price: "$20/night",
    sites: 11,
    elevation: "1,860 ft",
    icon: "🫎",
    gradient: "linear-gradient(135deg, #375344 0%, #1c2a23 100%)",
    description: "A rugged camp deep in spruce forest and glacial ponds, often used as a base for long summit days. Wildlife sightings are common around dawn.",
    reviews_list: [
      { author: "KnifeEdgeKay", stars: 5, text: "Remote feel with excellent trail access." },
      { author: "MooseMorning", stars: 5, text: "Saw moose twice before breakfast." },
      { author: "PondPath", stars: 4, text: "Simple camp, big wilderness payoff." },
    ],
  },
  {
    id: 36,
    name: "Silver Creek Narrows",
    location: "Sawtooth NRA, Idaho",
    state: "Idaho",
    rating: 4.7,
    reviews: 104,
    tags: ["Fishing", "Family", "Hiking"],
    amenities: ["Flush Toilets", "Water", "Picnic Shelters", "Fire Rings"],
    price: "$26/night",
    sites: 37,
    elevation: "6,180 ft",
    icon: "🏔️",
    gradient: "linear-gradient(135deg, #486b7a 0%, #24404c 100%)",
    description: "A creekside camp ringed by granite peaks with easy access to lakes and ridgeline trails. Anglers love the nearby waters for early morning sessions.",
    reviews_list: [
      { author: "SawtoothSam", stars: 5, text: "Beautiful setting and excellent hiking options." },
      { author: "CreekCast", stars: 4, text: "Great place to fish and unwind." },
      { author: "PeakLunch", stars: 5, text: "Perfect base for day hikes in all directions." },
    ],
  },
  {
    id: 37,
    name: "Cottonwood Wash Camp",
    location: "Bighorn Canyon NRA, Montana",
    state: "Montana",
    rating: 4.4,
    reviews: 69,
    tags: ["Wildlife", "Stargazing", "Photography"],
    amenities: ["Vault Toilets", "Boat Ramp", "Fire Rings"],
    price: "$14/night",
    sites: 17,
    elevation: "3,650 ft",
    icon: "🌙",
    gradient: "linear-gradient(135deg, #6a5b3e 0%, #352d1f 100%)",
    description: "Open canyon walls, sparse cottonwoods, and expansive skies define this dry-country camp. Great for birding, boating, and dark-night stargazing.",
    reviews_list: [
      { author: "CanyonCam", stars: 4, text: "Quiet and wide-open with great evening light." },
      { author: "RiverRim", stars: 5, text: "Excellent stars and very peaceful nights." },
      { author: "BoatBase", stars: 4, text: "Simple but convenient for the water." },
    ],
  },
  {
    id: 38,
    name: "Fern Hollow Camp",
    location: "Red River Gorge, Kentucky",
    state: "Kentucky",
    rating: 4.6,
    reviews: 93,
    tags: ["Hiking", "Family", "Pet-Friendly"],
    amenities: ["Flush Toilets", "Showers", "Water", "Camp Store"],
    price: "$22/night",
    sites: 42,
    elevation: "1,280 ft",
    icon: "🌿",
    gradient: "linear-gradient(135deg, #3b6a4a 0%, #1f3a29 100%)",
    description: "Surrounded by sandstone arches and thick hardwood forest, Fern Hollow is ideal for climbers and hikers who want easy access to classic Red River Gorge trails.",
    reviews_list: [
      { author: "ArchWalker", stars: 5, text: "Great base for arch hikes and climbing days." },
      { author: "ForestFox", stars: 4, text: "Convenient, clean, and close to everything." },
      { author: "RRGRegular", stars: 5, text: "Our go-to spot whenever we visit the Gorge." },
    ],
  },
  {
    id: 39,
    name: "Ponderosa Rim Camp",
    location: "Kaibab NF, Arizona",
    state: "Arizona",
    rating: 4.5,
    reviews: 82,
    tags: ["Tent", "Hiking", "Stargazing"],
    amenities: ["Vault Toilets", "Water", "Fire Rings", "Picnic Tables"],
    price: "$20/night",
    sites: 26,
    elevation: "7,400 ft",
    icon: "🌲",
    gradient: "linear-gradient(135deg, #5f6f3d 0%, #2e371f 100%)",
    description: "A cooler high-country camp above the desert floor with wide views and dense ponderosa shade. Good shoulder-season weather and generally calm evenings.",
    reviews_list: [
      { author: "RimRoamer", stars: 5, text: "Great temperature break from lower elevations." },
      { author: "CampJuniper", stars: 4, text: "Simple setup and excellent night sky." },
      { author: "AZHiker", stars: 4, text: "Nice trails and very peaceful campground." },
    ],
  },
  {
    id: 40,
    name: "Driftwood Point Camp",
    location: "Olympic Coast, Washington",
    state: "Washington",
    rating: 4.8,
    reviews: 137,
    tags: ["Ocean Views", "Hike-in", "Wildlife"],
    amenities: ["Composting Toilets", "Food Lockers", "Water Source Nearby"],
    price: "$31/night",
    sites: 13,
    elevation: "90 ft",
    icon: "🌊",
    gradient: "linear-gradient(135deg, #3a6078 0%, #1f3545 100%)",
    description: "A rugged beachside camp with giant driftwood, tide pools, and offshore sea stacks. Best experienced with a tide chart and a camera.",
    reviews_list: [
      { author: "SeaStackSue", stars: 5, text: "Absolutely breathtaking coastline and great wildlife." },
      { author: "TideTrack", stars: 5, text: "Plan your route with tides and you'll have a perfect trip." },
      { author: "CoastalCam", stars: 4, text: "One of the most scenic coastal camps in the PNW." },
    ],
  },
  {
    id: 41,
    name: "Sierra Pines Camp",
    location: "Inyo NF, California",
    state: "California",
    rating: 4.7,
    reviews: 121,
    tags: ["Hiking", "Fishing", "Family"],
    amenities: ["Flush Toilets", "Water", "Bear Boxes", "Picnic Tables"],
    price: "$27/night",
    sites: 34,
    elevation: "8,400 ft",
    icon: "🏕️",
    gradient: "linear-gradient(135deg, #456b5f 0%, #233a33 100%)",
    description: "A pine-shaded camp close to alpine lakes and long granite trails. Snowmelt streams keep the area cool into summer and draw anglers from across the region.",
    reviews_list: [
      { author: "HighLakeHank", stars: 5, text: "Fantastic trail access and super scenic surroundings." },
      { author: "GraniteGem", stars: 4, text: "Crowded weekends but still worth it." },
      { author: "PineTrail", stars: 5, text: "Great basecamp for multiple day hikes." },
    ],
  },
  {
    id: 42,
    name: "Cumberland Knob Camp",
    location: "Daniel Boone NF, Kentucky",
    state: "Kentucky",
    rating: 4.4,
    reviews: 66,
    tags: ["Family", "Hiking", "Waterfall"],
    amenities: ["Flush Toilets", "Showers", "Camp Store", "Playground"],
    price: "$21/night",
    sites: 47,
    elevation: "1,650 ft",
    icon: "🌄",
    gradient: "linear-gradient(135deg, #4d6a44 0%, #283724 100%)",
    description: "An accessible forest campground near cliff overlooks and creek-fed waterfalls. Great for mixed groups with kids and newer hikers.",
    reviews_list: [
      { author: "KnobNora", stars: 4, text: "Great family setup and nice nearby trails." },
      { author: "FallsFirst", stars: 5, text: "Loved the waterfall hikes from camp." },
      { author: "ForestLane", stars: 4, text: "Convenient and comfortable for a weekend." },
    ],
  },
  {
    id: 43,
    name: "Juniper Mesa Camp",
    location: "Pike NF, Colorado",
    state: "Colorado",
    rating: 4.6,
    reviews: 90,
    tags: ["Dispersed", "Hiking", "Photography"],
    amenities: ["Vault Toilets", "Trail Access", "Fire Rings"],
    price: "$15/night",
    sites: 20,
    elevation: "8,050 ft",
    icon: "📸",
    gradient: "linear-gradient(135deg, #6d563f 0%, #382d21 100%)",
    description: "A quiet mesa-top camp with broad views and easy access to pinyon-juniper trail networks. Sunrises are especially popular with photographers.",
    reviews_list: [
      { author: "MesaMorning", stars: 5, text: "Golden sunrise light every morning. Amazing." },
      { author: "FrontRangeFan", stars: 4, text: "Easy to access and surprisingly quiet." },
      { author: "DustBoots", stars: 4, text: "Simple amenities but excellent views." },
    ],
  },
  {
    id: 44,
    name: "Cold River Junction",
    location: "White Mountain NF, New Hampshire",
    state: "New Hampshire",
    rating: 4.8,
    reviews: 132,
    tags: ["Backcountry", "Hiking", "Fall Foliage"],
    amenities: ["Bear Boxes", "Water Pump", "Trailhead Access"],
    price: "$24/night",
    sites: 16,
    elevation: "2,300 ft",
    icon: "🍁",
    gradient: "linear-gradient(135deg, #78543c 0%, #3e2b1f 100%)",
    description: "A cool river-valley camp beneath steep forested slopes and notch trails. In autumn, nearby hardwood ridges turn bright orange and red.",
    reviews_list: [
      { author: "NotchNate", stars: 5, text: "Excellent access to classic White Mountains hikes." },
      { author: "LeafPeep", stars: 5, text: "Peak foliage here is unreal." },
      { author: "RiverStone", stars: 4, text: "Great camp, chilly nights, bring warm gear." },
    ],
  },
  {
    id: 45,
    name: "Prairie Creek Camp",
    location: "Flint Hills, Oklahoma",
    state: "Oklahoma",
    rating: 4.3,
    reviews: 49,
    tags: ["Prairie", "Wildlife", "Stargazing"],
    amenities: ["Pit Toilets", "Water Pump", "Fire Rings"],
    price: "$13/night",
    sites: 21,
    elevation: "1,220 ft",
    icon: "🌾",
    gradient: "linear-gradient(135deg, #7a6a3c 0%, #40361e 100%)",
    description: "Rolling grasslands, open skies, and long sunsets define this prairie camp. Birders and night sky watchers both love its remote setting.",
    reviews_list: [
      { author: "GrassSky", stars: 4, text: "Simple but beautiful, especially at dusk." },
      { author: "OpenRange", stars: 4, text: "Great stargazing with very little light pollution." },
      { author: "PrairiePat", stars: 5, text: "Quiet and peaceful, exactly what I wanted." },
    ],
  },
  {
    id: 46,
    name: "Windward Point Camp",
    location: "Lake Superior Shore, Minnesota",
    state: "Minnesota",
    rating: 4.7,
    reviews: 108,
    tags: ["Ocean Views", "Hiking", "Photography"],
    amenities: ["Flush Toilets", "Potable Water", "Picnic Tables", "Fire Rings"],
    price: "$29/night",
    sites: 29,
    elevation: "690 ft",
    icon: "🌬️",
    gradient: "linear-gradient(135deg, #426783 0%, #223747 100%)",
    description: "Perched above rocky Lake Superior shoreline, Windward Point offers cool breezes and dramatic weather. Great for shoreline hikes and storm watching.",
    reviews_list: [
      { author: "SuperiorSky", stars: 5, text: "Lake views were incredible and trails were fantastic." },
      { author: "ColdBreeze", stars: 4, text: "Can get windy, but worth it for the scenery." },
      { author: "NorthLens", stars: 5, text: "Excellent photo opportunities all day." },
    ],
  },
  {
    id: 47,
    name: "Copper Canyon Camp",
    location: "Gila NF, New Mexico",
    state: "New Mexico",
    rating: 4.5,
    reviews: 71,
    tags: ["Backcountry", "Wildlife", "Hiking"],
    amenities: ["Vault Toilets", "Bear Boxes", "Trail Access"],
    price: "$18/night",
    sites: 18,
    elevation: "6,700 ft",
    icon: "🦅",
    gradient: "linear-gradient(135deg, #7a573d 0%, #3b2b20 100%)",
    description: "A rugged canyon-edge camp in pine and juniper country with long switchback trails to creek bottoms and ridgelines.",
    reviews_list: [
      { author: "GilaGabe", stars: 5, text: "Excellent solitude and beautiful canyon views." },
      { author: "DesertPine", stars: 4, text: "Primitive but rewarding." },
      { author: "CanyonRidge", stars: 4, text: "Great wildlife sightings at dawn." },
    ],
  },
  {
    id: 48,
    name: "Moss Creek Camp",
    location: "Cherokee NF, Tennessee",
    state: "Tennessee",
    rating: 4.6,
    reviews: 84,
    tags: ["Family", "Waterfall", "Pet-Friendly"],
    amenities: ["Showers", "Flush Toilets", "Water", "Picnic Shelters"],
    price: "$24/night",
    sites: 39,
    elevation: "2,050 ft",
    icon: "🌧️",
    gradient: "linear-gradient(135deg, #3b644f 0%, #21372c 100%)",
    description: "A shady creekside campground with quick access to ferny ravines and low-elevation waterfall trails. Great in spring and early summer.",
    reviews_list: [
      { author: "CreekCalm", stars: 5, text: "Loved the creek sounds all night and easy waterfall hikes." },
      { author: "TrailPup", stars: 4, text: "Very pet-friendly and family-friendly." },
      { author: "RainFern", stars: 4, text: "Beautiful spot with solid amenities." },
    ],
  },
  {
    id: 49,
    name: "Summit Lake Spur",
    location: "Absaroka-Beartooth, Montana",
    state: "Montana",
    rating: 4.9,
    reviews: 116,
    tags: ["Backcountry", "Hiking", "Stargazing"],
    amenities: ["Bear Boxes", "Vault Toilets", "Lake Access"],
    price: "$27/night",
    sites: 14,
    elevation: "9,300 ft",
    icon: "⭐",
    gradient: "linear-gradient(135deg, #4e5f79 0%, #283243 100%)",
    description: "An alpine lake camp framed by talus slopes and jagged peaks. High elevation means clear nights, cold mornings, and huge star fields.",
    reviews_list: [
      { author: "AlpineNight", stars: 5, text: "Ridiculously beautiful setting with incredible stars." },
      { author: "LakeLooper", stars: 5, text: "Great basecamp for long alpine day hikes." },
      { author: "ColdCoffee", stars: 4, text: "Very cold nights, but absolutely worth it." },
    ],
  },
  {
    id: 50,
    name: "Hemlock Point Camp",
    location: "Superior NF, Minnesota",
    state: "Minnesota",
    rating: 4.7,
    reviews: 102,
    tags: ["Canoe", "Wildlife", "Family"],
    amenities: ["Canoe Launch", "Flush Toilets", "Water", "Fire Rings"],
    price: "$26/night",
    sites: 30,
    elevation: "1,480 ft",
    icon: "🦉",
    gradient: "linear-gradient(135deg, #355a4a 0%, #1c3127 100%)",
    description: "A northwoods lakeside camp with calm paddling routes, loon calls at dusk, and mixed pine-hardwood forest surrounding the sites.",
    reviews_list: [
      { author: "LoonLullaby", stars: 5, text: "Perfect canoe access and beautiful quiet evenings." },
      { author: "NorthCamp", stars: 4, text: "Great family site options and clean campground." },
      { author: "PaddlePath", stars: 5, text: "One of our favorite Minnesota camps." },
    ],
  },
];

const RATING_DISTRIBUTION = [2.8, 3.1, 3.3, 3.5, 3.7, 3.9, 4.1, 4.3, 4.5, 4.7, 4.9];

export const campsites = CAMPSITES_RAW.map((camp, index) => {
  const hasTent = camp.tags.includes('Tent');
  const hasRV = camp.tags.includes('RV');

  return {
    ...camp,
    rating: RATING_DISTRIBUTION[index % RATING_DISTRIBUTION.length],
    sites: Math.max(5, camp.sites),
    tags: hasTent || hasRV ? camp.tags : ['Tent', ...camp.tags],
  };
});