export const campsites = [
  {
    id: 1,
    name: "Pineridge Summit Camp",
    location: "Rocky Mountain NP, Colorado",
    state: "Colorado",
    rating: 4.8,
    reviews: 142,
    tags: ["Tent", "Pet-Friendly", "Hiking"],
    amenities: ["Fire Pits", "Flush Toilets", "Potable Water", "Picnic Tables"],
    price: "$28/night",
    sites: 34,
    elevation: "9,200 ft",
    icon: "🏔️",
    gradient: "linear-gradient(135deg, #3d5a3e 0%, #2d4a2d 100%)",
    description:
      "Perched above the treeline with panoramic views of the Continental Divide, Pineridge Summit offers an unforgettable high-altitude camping experience. Wake up to marmots and elk grazing just beyond your tent. Stellar dark skies make this a favorite for stargazers.",
    reviews_list: [
      { author: "MargaretH", stars: 5, text: "Absolutely breathtaking views. The sunrise over the peaks was worth every bit of the drive up." },
      { author: "TrailDog92", stars: 5, text: "We've been coming here for 4 years. The fire pits are well-maintained and the rangers are super helpful." },
      { author: "NightSkyNate", stars: 4, text: "Dark skies are incredible. Bring layers — temps drop fast after sunset even in July." },
    ],
  },
  {
    id: 2,
    name: "Whispering Pines Hollow",
    location: "Ozark NF, Arkansas",
    state: "Arkansas",
    rating: 4.5,
    reviews: 89,
    tags: ["RV", "Family", "Fishing"],
    amenities: ["Electric Hookups", "Dump Station", "Showers", "Fish Cleaning Station"],
    price: "$35/night",
    sites: 52,
    elevation: "1,400 ft",
    icon: "🌲",
    gradient: "linear-gradient(135deg, #4a6741 0%, #2e4a2e 100%)",
    description:
      "Tucked along a cold-water creek shaded by ancient shortleaf pines, Whispering Pines is a sanctuary for families and anglers alike. The creek runs clear year-round, filled with trout. Kids can spend entire afternoons catching crawdads while adults relax in hammocks.",
    reviews_list: [
      { author: "FishingFred", stars: 5, text: "Caught my limit every single morning. The creek is crystal clear and the campsite is gorgeous." },
      { author: "MomOf3Campers", stars: 4, text: "Perfect for families. Kids loved the creek and the staff was incredibly welcoming." },
      { author: "OzarkWanderer", stars: 5, text: "The pine smell in the morning is unlike anything else. Will be back every fall." },
    ],
  },
  {
    id: 3,
    name: "Redrock Canyon Basecamp",
    location: "Escalante, Utah",
    state: "Utah",
    rating: 4.9,
    reviews: 214,
    tags: ["Dispersed", "Hiking", "Photography"],
    amenities: ["Vault Toilets", "Bear Boxes", "Trailhead Access"],
    price: "$18/night",
    sites: 16,
    elevation: "5,800 ft",
    icon: "🏜️",
    gradient: "linear-gradient(135deg, #8b4513 0%, #5c3317 100%)",
    description:
      "Step into a Mars-like landscape of towering sandstone fins and slot canyons painted in every shade of red and orange. This primitive camp sits at the trailhead of four world-class canyon hikes. No crowds, no noise — just rock, sky, and stars.",
    reviews_list: [
      { author: "CanyonCrawler", stars: 5, text: "The slot canyon at sunrise is a religious experience. Get up early — it's worth it." },
      { author: "DesertPhotog", stars: 5, text: "Every direction is a shot. I've never deleted so few photos from a single trip." },
      { author: "BackpackBeth", stars: 4, text: "Very primitive, bring all your water. But the solitude is absolutely worth it." },
    ],
  },
  {
    id: 4,
    name: "Lakeshore Meadows",
    location: "Boundary Waters, Minnesota",
    state: "Minnesota",
    rating: 4.6,
    reviews: 178,
    tags: ["Canoe", "Pet-Friendly", "Paddling"],
    amenities: ["Canoe Launch", "Picnic Tables", "Fire Rings", "Vault Toilets"],
    price: "$22/night",
    sites: 28,
    elevation: "1,356 ft",
    icon: "🛶",
    gradient: "linear-gradient(135deg, #2c5f6e 0%, #1a3d4a 100%)",
    description:
      "Loons calling at dusk, moose wading in the shallows at dawn — Lakeshore Meadows drops you right into the legendary BWCA experience. Flat sites sit just steps from the water, perfect for portage trips or lazy days paddling the shoreline.",
    reviews_list: [
      { author: "PaddlePete", stars: 5, text: "Heard loons every single night. The canoe launch is in great shape and the sites have great lake views." },
      { author: "MNWilderness", stars: 4, text: "Bring bug spray in June, but the fishing and paddling make it 100% worth it." },
      { author: "QuietLakeLou", stars: 5, text: "Most peaceful place I've ever camped. Woke up to a moose literally ten feet from my tent." },
    ],
  },
  {
    id: 5,
    name: "Coastal Bluff Retreat",
    location: "Point Reyes NS, California",
    state: "California",
    rating: 4.7,
    reviews: 301,
    tags: ["Hike-in", "Ocean Views", "Wildlife"],
    amenities: ["Composting Toilets", "Food Lockers", "Water Spigot"],
    price: "$30/night",
    sites: 20,
    elevation: "240 ft",
    icon: "🌊",
    gradient: "linear-gradient(135deg, #2a5c8a 0%, #1a3a5c 100%)",
    description:
      "A 2-mile hike rewards you with a cliffside camp perched above the Pacific. Elephant seals bark on the beaches below, gray whales breach offshore in winter, and wildflowers carpet the bluffs in spring. One of the most dramatic camp settings on the West Coast.",
    reviews_list: [
      { author: "WhaleDan", stars: 5, text: "Saw four gray whales from camp in February. The sunsets here are surreal." },
      { author: "PtReyesRegular", stars: 5, text: "I've been here every year for 6 years. It never gets old. Book way in advance." },
      { author: "BluffHiker", stars: 4, text: "The hike in is easy and totally worth it. Mornings are foggy and magical." },
    ],
  },
  {
    id: 6,
    name: "Glacier Creek Flats",
    location: "North Cascades NP, Washington",
    state: "Washington",
    rating: 4.8,
    reviews: 95,
    tags: ["Backcountry", "Climbing", "Wildflowers"],
    amenities: ["Bear Canisters Required", "Vault Toilets", "Ranger Station Nearby"],
    price: "$20/night",
    sites: 12,
    elevation: "4,100 ft",
    icon: "❄️",
    gradient: "linear-gradient(135deg, #3a6b8a 0%, #1e3f5a 100%)",
    description:
      "Surrounded by jagged peaks and fed by milky glacial meltwater, this remote camp is a paradise for alpinists and wildflower enthusiasts. The meadows burst into color July–August, and the creek crossing into camp makes for an adventurous entrance.",
    reviews_list: [
      { author: "AlpineAli", stars: 5, text: "The wildflowers in late July are absolutely insane. Like walking through a painting." },
      { author: "CascadesClimber", stars: 5, text: "Used as a base for a 3-day ridge traverse. Perfect location, clean water nearby." },
      { author: "GlacierGazer", stars: 4, text: "Get permits early — this fills up fast. Worth every bit of the effort." },
    ],
  },
  {
    id: 7,
    name: "Longleaf Pine Bottoms",
    location: "Kisatchie NF, Louisiana",
    state: "Louisiana",
    rating: 4.3,
    reviews: 61,
    tags: ["Family", "Birding", "Quiet"],
    amenities: ["Flush Toilets", "Hot Showers", "Playgrounds", "Picnic Shelters"],
    price: "$24/night",
    sites: 44,
    elevation: "240 ft",
    icon: "🌿",
    gradient: "linear-gradient(135deg, #4a6a3a 0%, #2d4a20 100%)",
    description:
      "A hidden gem in the Deep South, this longleaf pine forest is one of the rarest ecosystems in North America. Birdwatchers flock here for red-cockaded woodpeckers and painted buntings. Warm nights, fireflies, and the smell of pine resin define the experience.",
    reviews_list: [
      { author: "BirdLadySue", stars: 5, text: "Spotted 34 species in one morning walk. The longleaf ecosystem is incredibly special." },
      { author: "SouthernCamper", stars: 4, text: "Very well-maintained campground. The facilities are clean and the staff is friendly." },
      { author: "FireflyFan", stars: 4, text: "Come in June for the fireflies. It looks like the whole forest is twinkling." },
    ],
  },
  {
    id: 8,
    name: "Thunder Basin Prairie Camp",
    location: "Thunder Basin NG, Wyoming",
    state: "Wyoming",
    rating: 4.4,
    reviews: 47,
    tags: ["Dispersed", "Wildlife", "Stargazing"],
    amenities: ["Vault Toilets", "Fire Rings"],
    price: "$10/night",
    sites: 8,
    elevation: "4,900 ft",
    icon: "⭐",
    gradient: "linear-gradient(135deg, #6b5a2a 0%, #3d3215 100%)",
    description:
      "Endless rolling prairie under a sky that seems twice as big as anywhere else. Pronghorn antelope graze at the edge of camp, and the Milky Way stretches from horizon to horizon on clear nights. True wide-open-spaces camping at its most honest.",
    reviews_list: [
      { author: "PronghorPaul", stars: 5, text: "Woke up surrounded by 40 pronghorn antelope. Absolute bucket-list morning." },
      { author: "DarkSkyStan", stars: 5, text: "Zero light pollution. Genuinely the best stars I've ever seen in the lower 48." },
      { author: "PrairieWalker", stars: 4, text: "Very basic facilities, but that's the point. Bring everything you need." },
    ],
  },
  {
    id: 9,
    name: "Hemlock Hollow Retreat",
    location: "Monongahela NF, West Virginia",
    state: "West Virginia",
    rating: 4.6,
    reviews: 112,
    tags: ["Family", "Fly Fishing", "Waterfalls"],
    amenities: ["Flush Toilets", "Hot Showers", "Potable Water", "Picnic Tables"],
    price: "$26/night",
    sites: 38,
    elevation: "2,800 ft",
    icon: "🌊",
    gradient: "linear-gradient(135deg, #2d5a3d 0%, #1a3d28 100%)",
    description:
      "Nestled in a cool hemlock-shaded gorge where two cold-water trout streams meet, this camp has everything: great fishing, easy waterfall hikes, and a family-friendly atmosphere. The hemlock canopy keeps things 10° cooler than the valley floor all summer.",
    reviews_list: [
      { author: "TroutWhisperer", stars: 5, text: "The Elk River section here is world-class for wild trout. Incredible experience." },
      { author: "WVNatureFan", stars: 4, text: "Visited in October for fall colors and it blew me away. Very underrated." },
      { author: "CoolCampCarl", stars: 5, text: "Escaped 95-degree heat in the valley and camped in 72-degree bliss. Worth the drive." },
    ],
  },
  {
    id: 10,
    name: "Saguaro Dusk Camp",
    location: "Sonoran Desert, Arizona",
    state: "Arizona",
    rating: 4.5,
    reviews: 88,
    tags: ["Desert", "Stargazing", "Photography"],
    amenities: ["Vault Toilets", "Water Station", "Ramadas"],
    price: "$20/night",
    sites: 22,
    elevation: "2,600 ft",
    icon: "🌵",
    gradient: "linear-gradient(135deg, #7a4e2d 0%, #4a2d15 100%)",
    description:
      "Camp among 150-year-old saguaro cacti as the sun sets the sky ablaze with orange and violet. Elf owls nest in the cacti overhead, Gila woodpeckers hammer at dawn, and coyotes serenade the moon. Winter camping here is mild and magical.",
    reviews_list: [
      { author: "DesertDawnDave", stars: 5, text: "The sunset colors reflecting off the saguaros are beyond words. Pure magic." },
      { author: "SonoranSally", stars: 5, text: "Owls hooting all night, roadrunner at breakfast. Desert birding paradise." },
      { author: "WinterCamper", stars: 4, text: "December here is perfect — cool days, cold nights, zero bugs. Ideal." },
    ],
  },
  {
    id: 11,
    name: "Foggy Hollow Cove",
    location: "Acadia NP, Maine",
    state: "Maine",
    rating: 4.7,
    reviews: 189,
    tags: ["Ocean Views", "Hiking", "Kayaking"],
    amenities: ["Flush Toilets", "Hot Showers", "Kayak Storage", "Ranger Programs"],
    price: "$32/night",
    sites: 30,
    elevation: "140 ft",
    icon: "🦞",
    gradient: "linear-gradient(135deg, #2a4a6a 0%, #152a3d 100%)",
    description:
      "Rocky Maine coastline, lobster boats in the fog, and the cry of seagulls over spruce forest — Foggy Hollow Cove is New England camping at its most atmospheric. Just outside Acadia's network of carriage roads, it's a perfect base for cyclists and hikers.",
    reviews_list: [
      { author: "MaineShoreMarcy", stars: 5, text: "Went for the lobster rolls, stayed for the incredible fog and coastline." },
      { author: "AcadiaCyclist", stars: 5, text: "Biked every carriage road in the park from this camp. Couldn't be better located." },
      { author: "FogLover", stars: 4, text: "The morning fog rolling in off the ocean is hauntingly beautiful. Very peaceful." },
    ],
  },
  {
    id: 12,
    name: "Aspen Grove High Camp",
    location: "White River NF, Colorado",
    state: "Colorado",
    rating: 4.9,
    reviews: 203,
    tags: ["Tent", "Fall Foliage", "Hiking"],
    amenities: ["Vault Toilets", "Water", "Fire Rings", "Trailhead Parking"],
    price: "$22/night",
    sites: 18,
    elevation: "10,400 ft",
    icon: "🍂",
    gradient: "linear-gradient(135deg, #7a6a2a 0%, #4a3e15 100%)",
    description:
      "In late September, this high-elevation camp transforms into a cathedral of gold as thousands of aspen trees turn simultaneously. The shimmering of leaves in the mountain breeze is a phenomenon you'll hear before you see. Book months ahead for peak fall.",
    reviews_list: [
      { author: "AspenAdmirer", stars: 5, text: "Peak fall weekend was absolutely transcendent. The sound of aspen leaves is otherworldly." },
      { author: "ColoradoCarrie", stars: 5, text: "Hiked to a 13er from camp. Views were incredible. Aspen groves turned perfectly." },
      { author: "FallFoliageFan", stars: 5, text: "Drove 6 hours for this. Zero regrets. Will be back every single October." },
    ],
  },
  {
    id: 13,
    name: "Bayou Cypress Camp",
    location: "Atchafalaya Basin, Louisiana",
    state: "Louisiana",
    rating: 4.2,
    reviews: 53,
    tags: ["Paddling", "Wildlife", "Unique"],
    amenities: ["Canoe Launch", "Pit Toilets", "Covered Pavilion"],
    price: "$15/night",
    sites: 10,
    elevation: "12 ft",
    icon: "🐊",
    gradient: "linear-gradient(135deg, #2a4a2a 0%, #152a15 100%)",
    description:
      "The largest river swamp in North America, the Atchafalaya offers a camping experience unlike anywhere else in the US. Ancient bald cypress draped in Spanish moss rise from the dark water. Alligators, herons, and roseate spoonbills are your neighbors.",
    reviews_list: [
      { author: "SwampSteve", stars: 5, text: "Paddled for 3 days through cypress groves. Felt like a different world entirely." },
      { author: "WildlifeWatcher", stars: 4, text: "Saw 3 alligators, 12 species of birds, and a nutria on day one. Unbelievable." },
      { author: "LouisianaLocal", stars: 4, text: "Basic facilities but the natural beauty is off the charts. Come at sunrise." },
    ],
  },
  {
    id: 14,
    name: "Tundra Rim Outpost",
    location: "Denali NP, Alaska",
    state: "Alaska",
    rating: 4.8,
    reviews: 74,
    tags: ["Backcountry", "Wildlife", "Midnight Sun"],
    amenities: ["Bear-Resistant Containers Required", "Bus Access Only", "Ranger Patrol"],
    price: "$16/night",
    sites: 6,
    elevation: "3,900 ft",
    icon: "🐻",
    gradient: "linear-gradient(135deg, #2d4a5c 0%, #152530 100%)",
    description:
      "One of the most remote and raw camping experiences in the national park system. Accessible only by park bus, the tundra here offers grizzly bear sightings, caribou migrations, and in summer, 20+ hours of daylight. Denali herself dominates the western horizon.",
    reviews_list: [
      { author: "AlaskaAlex", stars: 5, text: "Grizzly with two cubs walked through camp at 2am. Still light outside. Alaska is unreal." },
      { author: "MidnightSunMeg", stars: 5, text: "Sat outside reading at midnight in full daylight. Surreal and unforgettable." },
      { author: "DenaliDreamer", stars: 5, text: "Hardest permit to get in Alaska. Worth every year I waited on the waitlist." },
    ],
  },
  {
    id: 15,
    name: "Blue Ridge Ridgeline",
    location: "Shenandoah NP, Virginia",
    state: "Virginia",
    rating: 4.5,
    reviews: 267,
    tags: ["Family", "Skyline Drive", "Fall Foliage"],
    amenities: ["Flush Toilets", "Showers", "Camp Store", "Amphitheater"],
    price: "$30/night",
    sites: 65,
    elevation: "3,600 ft",
    icon: "🌄",
    gradient: "linear-gradient(135deg, #3d5a3e 0%, #253525 100%)",
    description:
      "Sitting astride the crest of the Blue Ridge with sweeping valley views east and west, this is Shenandoah's most beloved frontcountry camp. Deer wander through sites at dusk, and the Appalachian Trail passes directly through the campground.",
    reviews_list: [
      { author: "ShenandoahSam", stars: 5, text: "AT through-hikers camping next to us shared wild stories. Magical community vibe." },
      { author: "DrivingTheDrive", stars: 4, text: "Perfect base for Skyline Drive. Very well-run, great amenities for families." },
      { author: "ValleyViewer", stars: 5, text: "Watched the fog fill the valley below at sunrise from my camp chair. Spectacular." },
    ],
  },
  {
    id: 16,
    name: "Lava Tube Basecamp",
    location: "Craters of the Moon NM, Idaho",
    state: "Idaho",
    rating: 4.4,
    reviews: 82,
    tags: ["Unique", "Geology", "Dark Sky"],
    amenities: ["Flush Toilets", "Potable Water", "Visitor Center Access"],
    price: "$20/night",
    sites: 42,
    elevation: "5,900 ft",
    icon: "🌋",
    gradient: "linear-gradient(135deg, #3a3a3a 0%, #1a1a1a 100%)",
    description:
      "Camp on a literal lava flow at one of America's most otherworldly landscapes. During the day, explore lava tubes, spatter cones, and obsidian flows. At night, a certified International Dark Sky Park delivers some of the most spectacular stargazing in the West.",
    reviews_list: [
      { author: "GeoGeek", stars: 5, text: "Crawled through a 1,000-foot lava tube. Absolutely prehistoric and incredible." },
      { author: "StargazerStan", stars: 5, text: "No moon, no light pollution, billions of stars. The Milky Way above black lava. Wow." },
      { author: "MoonScapeMaria", stars: 4, text: "Feels like another planet. Hot during the day but stunning in every direction." },
    ],
  },
  {
    id: 17,
    name: "Smoky Holler Hollow",
    location: "Great Smoky Mountains NP, Tennessee",
    state: "Tennessee",
    rating: 4.6,
    reviews: 345,
    tags: ["Family", "Waterfall", "Fall Foliage"],
    amenities: ["Flush Toilets", "Hot Showers", "Accessible Sites", "Amphitheater"],
    price: "$29/night",
    sites: 80,
    elevation: "1,800 ft",
    icon: "🌫️",
    gradient: "linear-gradient(135deg, #3d5c3d 0%, #1e2e1e 100%)",
    description:
      "Wrapped in the perpetual blue haze that gives these mountains their name, this beloved camp sits next to a rushing mountain stream. Synchronous fireflies in June draw visitors from around the world, and the fall colors rival anywhere in America.",
    reviews_list: [
      { author: "FireflyChaser", stars: 5, text: "Synchronous fireflies are a genuine natural wonder. Everyone should see this once." },
      { author: "SmokyMountainMom", stars: 5, text: "Brought 3 kids and they all said it was their favorite camping trip ever." },
      { author: "HazeHiker", stars: 4, text: "Crowded in peak season but the surrounding wilderness makes it worth it." },
    ],
  },
  {
    id: 18,
    name: "Mesa Verde Starcamp",
    location: "Mesa Verde NP, Colorado",
    state: "Colorado",
    rating: 4.7,
    reviews: 156,
    tags: ["Cultural", "Stargazing", "History"],
    amenities: ["Flush Toilets", "Showers", "Gift Shop", "Evening Programs"],
    price: "$34/night",
    sites: 45,
    elevation: "7,000 ft",
    icon: "🏺",
    gradient: "linear-gradient(135deg, #6b4a2a 0%, #3d2510 100%)",
    description:
      "Camp on the same mesa where Ancestral Puebloans built their remarkable cliff dwellings over 700 years ago. Ranger-led evening programs bring history to life, and the high desert elevation means cool nights and jaw-dropping star density overhead.",
    reviews_list: [
      { author: "HistoryHiker", stars: 5, text: "The evening cliff dwelling tour by torchlight was one of the best experiences of my life." },
      { author: "DesertDreamer", stars: 4, text: "Woke up to a brilliant sunrise over the canyon. Made breakfast feeling like an ancient farmer." },
      { author: "MesaMarco", stars: 5, text: "Perfect mix of culture, nature, and stars. Bring a good sleeping bag for cold nights." },
    ],
  },
  {
    id: 19,
    name: "Tallgrass Prairie Vista",
    location: "Flint Hills, Kansas",
    state: "Kansas",
    rating: 4.3,
    reviews: 39,
    tags: ["Prairie", "Birding", "Solitude"],
    amenities: ["Pit Toilets", "Water Pump", "Fire Rings"],
    price: "$12/night",
    sites: 14,
    elevation: "1,440 ft",
    icon: "🌾",
    gradient: "linear-gradient(135deg, #7a6a3a 0%, #4a3e1e 100%)",
    description:
      "One of the last remaining tallgrass prairie ecosystems in North America. Wind waves through 8-foot bluestem grass around your tent, greater prairie chickens boom at dawn, and the treeless horizon stretches forever in every direction. Rare, beautiful solitude.",
    reviews_list: [
      { author: "PrairiePhil", stars: 5, text: "The wind in the tallgrass sounds like the ocean. Completely meditative experience." },
      { author: "GrasslandBirder", stars: 4, text: "Dickcissels, bobolinks, prairie chickens — incredible grassland birding." },
      { author: "SolitudeSeeker", stars: 5, text: "Camped here alone for 3 nights. Perfect peace. Most people don't even know this exists." },
    ],
  },
  {
    id: 20,
    name: "Olympic Rainforest Camp",
    location: "Hoh Rainforest, Washington",
    state: "Washington",
    rating: 4.8,
    reviews: 221,
    tags: ["Rainforest", "Wildlife", "Photography"],
    amenities: ["Flush Toilets", "Potable Water", "Amphitheater", "Accessible Trails"],
    price: "$24/night",
    sites: 36,
    elevation: "578 ft",
    icon: "🌿",
    gradient: "linear-gradient(135deg, #2a5a3a 0%, #152a1e 100%)",
    description:
      "The Hoh is one of only four temperate rainforests in the world, and camping here feels like stepping into a Tolkien novel. Massive old-growth Sitka spruce draped in club moss, Roosevelt elk grazing in clearings, and the absolute silence of 140 inches of annual rainfall absorbed by millennia of moss.",
    reviews_list: [
      { author: "MossAndMist", stars: 5, text: "The Hall of Mosses at dusk felt ancient and sacred. Truly one of earth's special places." },
      { author: "RooseveltRandy", stars: 5, text: "Huge elk herd walked through camp at sunrise. Incredible, quiet, humbling." },
      { author: "RainLover", stars: 4, text: "It rained the whole time and I didn't care at all. The forest just comes alive in rain." },
    ],
  },
];